### ISSUE TITLE
issues with preprocessor warnings in packages using Rcpp

### ISSUE THREAD

**Issue by kotoroshinoto** [kazi11/TestPackage#1]
I was told to bring this issue to r-devel or r-package-devel

referencing this RcppEigen issue: https://github.com/RcppCore/RcppEigen/issues/74

is their understanding of CRAN policy accurate? 

to me this doesn't make sense.

There is a distinct difference between preventing the occurence of an inappropriate line of code (i.e. a pragma directive that some versions of a compiler cannot understand or use and will issue complaints about) from being provided the compiler, and merely silencing a warning that the compiler would otherwise be issuing (i.e. using a -Wno-warnings style flag to hide the complaint instead of preventing the condition that creates the complaint).

I do not think that these things are actually equivalent, but i'm being told that CRAN will treat that as equivalent to warning-silencing.

That doesn't make sense. It results in bad programming practices, such as leaving in preprocessor directives for platforms that cannot understand them. 

In any other context, platform specific preprocessor driven inclusion or exclusion of code to ensure that only appropriate code is used for a given compiler or platform would not be objected to, so why would this be a problem?

**Comment by kotoroshinoto** [comment]
I presume the line "Packages should not attempt to disable compiler diagnostics, nor to remove other diagnostic information such as symbols in shared objects." is what is driving this interpretation.

Not providing a directive to the preprocessor when it is not appropriate and not supported for either the platform or the compiler itself is not tampering or disabling a diagnostic.

Trying to silence the warning with a -Wno flag WOULD be doing that, but wrapping the pragma in a conditional so that it only exists when it will have a functional utility is no different from having OS specific implementation files. It certainly would have the effect of the warning no longer being issued, but that would be because the errant lines are never provided to the preprocessor in the first place, which itself is actually an error, and as such should NOT be the state of affairs that CRAN policy demands.

it is entirely backward from what one ought to expect a developer to do.

**Comment by jstaf** [comment]
I think you might be posting in the wrong place. r-package-devel refers to an official R mailing list - this repo is just a little R packaging tutorial I created on Github a few years ago that happens to share the same name.
